DistribuidoraApp/Controllers/RemitosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DistribuidoraAPI.Extensions;
using DistribuidoraAPI.Models;
using iTextSharp.text;
using iTextSharp.text.pdf;
using Microsoft.Reporting.WebForms;
using Negocio.entidades;
using Negocio.enumeradores;

namespace DistribuidoraAPI.Controllers
{
    [Authorize(Roles = "Administracion, Desarrollo")]
    //[SessionExpire]
    public class RemitosController : Controller
    {
        private DistribuidoraDBEntities db = new DistribuidoraDBEntities();

        // GET: Remitos
        public ActionResult Index(string mensaje, string tipoMensaje, int? VentaId)
        {
            ViewBag.mensaje = mensaje;
            ViewBag.tipoMensaje = tipoMensaje;
            ViewBag.ClienteId = new SelectList(db.Cliente.Where(x => x.Activo == true), "ClienteId", "RazonSocial");
            ViewBag.TransportistaId = new SelectList(db.Transportista.Where(x => x.Activo == true), "TransportistaId", "Nombre");
            var ventas = db.Venta.Select(x => new
            {
                Text = "ID: " + x.VentaId.ToString() + " - $" + x.Final + " - " + x.Fecha,
                Value = x.VentaId
            }).OrderByDescending(x => x.Value).ToList();


            DateTime FechaDesde = DateTime.Now.AddDays(-1); TimeSpan ts = new TimeSpan(0, 0, 0);
            DateTime FechaHasta = DateTime.Now; TimeSpan ts1 = new TimeSpan(23, 59, 59);
            List<Remito> listRemitos = new List<Remito>();
            listRemitos = db.Remito
                             .Include(v => v.Cliente)
                             .Include(v => v.Venta)
                             .Where(x => x.FechaCreacion >= FechaDesde && x.FechaCreacion <= FechaHasta && x.Activo == true)
                             .OrderByDescending(x => x.RemitoId)
                             .ToList();

            if (VentaId != null)
            {
                ViewBag.VentaId = new SelectList(ventas, "Value", "Text", (int)VentaId);
                listRemitos = listRemitos.Where(x => x.VentaId == VentaId).ToList();
            }
            else
            {
                ViewBag.VentaId = new SelectList(ventas, "Value", "Text");
            }
            return View(listRemitos);
        }

        [HttpPost]
        public ActionResult IndexBusqueda(int? ClienteId, int? TransportistaId, string fechas, int? VentaId)
        {
            List<Remito> listRemitos = new List<Remito>();

            string[] arrayFechas = fechas.Split('-');
            string desde = arrayFechas[0].Trim();
            string hasta = arrayFechas[1].Trim();
            DateTime FechaDesde = Convert.ToDateTime(desde);
            TimeSpan ts = new TimeSpan(0, 0, 0);
            //FechaDesde = FechaDesde.Date + ts;
            DateTime FechaHasta = Convert.ToDateTime(hasta);
            TimeSpan ts1 = new TimeSpan(23, 59, 59);
            FechaHasta = FechaHasta.Date + ts1;
            int PerfilId = Convert.ToInt32(User.Identity.GetPerfilId());
            //int TipoVentaId = (PerfilId == (int)PerfilE.Preventista) ? (int)TipoVentaE.Remota : (int)TipoVentaE.Presencial;

            //if (PerfilId == (int)PerfilE.Administracion || PerfilId == (int)PerfilE.Desarrollo)
            //{
            listRemitos = db.Remito.Include(v => v.Cliente)
                         .Include(v => v.Venta)
                         .Where(x => x.Activo == true)
                         .OrderByDescending(x => x.RemitoId)
                         .Where(x => x.FechaCreacion >= FechaDesde && x.FechaCreacion <= FechaHasta).ToList();
            //}
            //else
            //{
            //    listVentas = db.Venta
            //                 .Include(v => v.Cliente)
            //                 .Include(v => v.Sucursal)
            //                 .Include(v => v.TipoCobro)
            //                 .Include(v => v.TipoVenta)
            //                 .Where(x => x.Fecha >= FechaDesde && x.Fecha <= FechaHasta && x.Activo == true && x.TipoVentaId == TipoVentaId)
            //                 .OrderByDescending(x => x.VentaId)
            //                 .ToList();
            //}


            if (TransportistaId != null)
            {
                listRemitos = listRemitos.Where(x => x.TransportistaId == TransportistaId).ToList();
            }
            if (ClienteId != null)
            {
                listRemitos = listRemitos.Where(x => x.ClienteId == ClienteId).ToList();
            }
            if (VentaId != null)
            {
                listRemitos = listRemitos.Where(x => x.VentaId == VentaId).ToList();
            }

            if (TransportistaId != null)
            {
                decimal total = 0;
                listRemitos.ForEach(x =>
                {
                    total += (decimal)x.Venta.Final;
                });
                ViewBag.TotalTransportista = total;
            }

            return PartialView("_Index", listRemitos);
        }

        // GET: Remitos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Remito remito = db.Remito.Find(id);
            if (remito == null)
            {
                return HttpNotFound();
            }
            return PartialView("_Details", remito);
        }

        // GET: Remitos/Create
        public ActionResult Create(int? VentaId)
        {
            if (VentaId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

                //ViewBag.VentaId = (int)VentaId;
                //Venta oVenta = db.Venta.Find((int)VentaId);
                //ViewBag.Descripcion = "Monto: $" + oVenta.Final + " - Fecha: " + oVenta.Fecha;
                //ViewBag.Venta = oVenta;
            }
            else
            {
                var ventas = db.Venta.Select(x => new
                {
                    Text = "ID: " + x.VentaId.ToString() + " - $" + x.Final + " - " + x.Fecha,
                    Value = x.VentaId
                }).OrderByDescending(x => x.Value).ToList();
                ViewBag.VentaId = new SelectList(ventas, "Value", "Text", VentaId);
            }
            var transportista = db.Transportista.Where(x => x.Activo == true).Select(x => new
            {
                Text = x.Nombre + ", " + x.Apellido,
                Value = x.TransportistaId
            }).ToList();

            ViewBag.TransportistaId = new SelectList(transportista, "Value", "Text");

            Venta oVenta = db.Venta.Find(VentaId);
            ViewBag.ClienteId = new SelectList(db.Cliente, "ClienteId", "RazonSocial", oVenta.ClienteId);

            var preventistas = db.AspNetUsers.Where(x => x.PerfilId == (int)PerfilE.Preventista).Select(x => new
            {
                Text = x.Nombre + ", " + x.Apellido,
                Value = x.UsuarioId
            }).ToList();
            ViewBag.PreventistaId = new SelectList(preventistas, "Value", "Text");

            Remito oRemitoVenta = db.Remito.Where(x => x.VentaId == VentaId && x.Activo == true).FirstOrDefault();
            if (oRemitoVenta != null)
            {
                ViewBag.RemitoCreadoTitulo = "Ya existe un remito creado con el N° " + oRemitoVenta.RemitoId.ToString();
                ViewBag.RemitoCreado = "Datos del Remito. Fecha: " + oRemitoVenta.FechaCreacion.ToString("dd/MM/yyyy") +
                    ". Cliente: " + oRemitoVenta.Cliente.RazonSocial +
                    ". Transportista: " + oRemitoVenta.Transportista.Apellido + ", " + oRemitoVenta.Transportista.Nombre +
                    ". CUIDADO! Si crea un nuevo Remito, se reemplaza al actual. Desea continuar?";
            }

            Remito oRemito = new Remito()
            {
                Fecha = DateTime.Now.ToString("MM/dd/yyyy")
            };
            return View(oRemito);
        }

        // POST: Remitos/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ClienteId,VentaId,Fecha,TransportistaId,Observaciones")] Remito remito)
        {
            if (ModelState.IsValid)
            {
                Remito oRemitoVenta = db.Remito.Where(x => x.VentaId == remito.VentaId && x.Activo == true).FirstOrDefault();
                if (oRemitoVenta != null)
                {
                    oRemitoVenta.Activo = false;
                    db.Entry(oRemitoVenta).State = EntityState.Modified;
                    db.SaveChanges();
                }

                Cliente oCliente = db.Cliente.Find(remito.ClienteId);
                remito.Domicilio = oCliente.Direccion;
                remito.CUIT = oCliente.CUIT;
                remito.Activo = true;
                remito.FechaCreacion = DateTime.Now;
                string UsuarioId = User.Identity.GetUsuarioId();
                remito.UsuarioId = Convert.ToInt32(UsuarioId);
                db.Remito.Add(remito);

                Venta oVenta = db.Venta.Find(remito.VentaId);
                oVenta.ClienteId = remito.ClienteId;
                oVenta.EstadoId = (int)EstadoE.Despachado;
                db.Entry(oVenta).State = EntityState.Modified;

                db.SaveChanges();
                Transportista transportista = db.Transportista.Find(remito.TransportistaId);
                transportista.FechaUltimoTransporte = DateTime.Now;
                transportista.MontoAcumulado += db.Venta.Find(remito.VentaId).Final;
                db.Entry(transportista).State = EntityState.Modified;
                db.SaveChanges();

DistribuidoraApp/Views/Remitos/Create.cshtml
@model Negocio.entidades.Remito
@using Negocio.entidades
@{
    ViewBag.Title = "Create";
    Venta oVenta = (Venta)ViewBag.Venta;
}

<div class="row">
    <div class="col-md-8">
        <h2>Crear Nuevo Remito</h2>
    </div>
    <div class="col-md-4">
        <div>
            @if (oVenta == null)
            {
                @Html.ActionLink("Volver al listado", "Index", null, new { @class = "btn btn-warning pull-right" })
            }
            else
            {
                @Html.ActionLink("Volver al listado", "Index", "Ventas", null, new { @class = "btn btn-warning pull-right" })
            }
        </div>
    </div>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div id="formRemito" class="form-horizontal form">

        <hr />

        @if (ViewBag.Venta == null)
        {

            <div class="form-group">
                @Html.LabelFor(model => model.VentaId, "Pedido", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("VentaId", null, "Seleccionar...", htmlAttributes: new { @class = "form-control", @required = "required" })
                    @Html.ValidationMessageFor(model => model.VentaId, "", new { @class = "text-danger" })
                </div>
            </div>
        }
        else
        {
            <div class="row">
                <div class="col-md-12">
                    @Html.Hidden("VentaId", (int)ViewBag.VentaId)
                    <div class="card">
                        <div class="card-header">
                            Datos del pedido
                        </div>
                        <div class="card-body">
                            <h5 class="card-title">Pedido: @oVenta.VentaId</h5>
                            <p class="card-text">@ViewBag.Descripcion</p>
                        </div>
                    </div>
                    <hr />
                </div>
            </div>

        }
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ClienteId, "Cliente", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ClienteId", null, "Seleccionar...", htmlAttributes: new { @class = "form-control", @required = "required" })
                @Html.ValidationMessageFor(model => model.ClienteId, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.TransportistaId, "Transportista", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TransportistaId", null, "Seleccionar...", htmlAttributes: new { @class = "form-control", @required = "required" })
                @Html.ValidationMessageFor(model => model.TransportistaId, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.Fecha, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fecha, new { htmlAttributes = new { @class = "form-control datepicker1", @readonly = "true", @required = "required" } })
                @Html.ValidationMessageFor(model => model.Fecha, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Observaciones, htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Observaciones, new { htmlAttributes = new { @class = "form-control " } })
                @Html.ValidationMessageFor(model => model.Observaciones, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Crear Remito" class="btn btn-outline-success submit" />
            </div>
        </div>
    </div>
}



@section scripts{
    <script src="~/Scripts/modernizr-2.8.3.js"></script>

    <script type="text/javascript">
        $('.datepicker1').datepicker({
            format: "mm/dd/yyyy",
            language: 'es',
            todayBtn: "linked",
            keyboardNavigation: false,
            forceParse: false,
            autoclose: true
        });

        $(document).ready(function () {
            var mensaje = '@ViewBag.RemitoCreado';
            var mensajeTitulo = '@ViewBag.RemitoCreadoTitulo';
            if (mensaje != '') {
                Swal.fire({
                    title: mensajeTitulo,
                    text: mensaje,
                    icon: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#3085d6',
                    cancelButtonColor: '#d33',
                    confirmButtonText: 'Sí, continuar!',
                    cancelButtonText: 'Cancelar'
                }).then((result) => {
                    if (!result.isConfirmed) {
                         window.location = '@Url.Action("Index")';
                    }
                });
            }
        })

    </script>

}

DistribuidoraApp/Views/Remitos/Index.cshtml
@model IEnumerable<Negocio.entidades.Remito>
@using Microsoft.AspNet.Identity;
@using DistribuidoraAPI.Extensions;
@{
    ViewBag.Title = "Listado de Remitos";
}

<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />

<link href="https://unpkg.com/multiple-select@1.5.2/dist/multiple-select.min.css" rel="stylesheet">

<script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment-with-locales.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>

<div class="row">
    <div class="col-md-12">
        <div class="row">
            <div class="col-md-12">
                <div class="row">
                    <div class="col-md-6"><h2>Listado de Remitos</h2></div>
                    <div class="col-md-6">
                        @Html.ActionLink("Volver al Inicio", "Index", "Home", null, new { @class = "btn btn-outline btn-warning pull-right" })

                        @*@Html.ActionLink("Crear Nuevo Remito", "Create", null, new { @class = "btn btn-outline btn-success pull-right" })*@
                        @Html.ActionLink("Volver a Ventas", "Index", "Ventas", null, new { @class = "btn btn-outline btn-warning pull-right", @id = "btnVentas", @hidden = "hidden" })
                    </div>
                </div>
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    @using (Ajax.BeginForm("IndexBusqueda", "Remitos", null, new AjaxOptions
                    {
                        HttpMethod = "POST",
                        OnBegin = "onBeginSubmit",
                        OnComplete = "onCompleteSubmit",
                        OnFailure = "onFailureResult",
                        OnSuccess = "onSuccessResult",
                        UpdateTargetId = "divTable",
                        InsertionMode = InsertionMode.Replace
                    }, new { id = "AjaxForm" }))
                    {
                        <div class="card-header">Filtros</div>
                        <div class="card-body">

                            <div class="row">
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label class="control-label">Rango de Fechas</label>
                                        <div id="reportrange"
                                             style="background: #fff; cursor: pointer; padding: 5px 10px; border: 1px solid #ccc">
                                            <i class="fa fa-calendar"></i>&nbsp;
                                            <span></span> <i class="fa fa-caret-down"></i>
                                            <input type="hidden" id="txtFechas" name="fechas" value="" />
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        @Html.Label("Transportista", "Transportista", htmlAttributes: new { @class = "control-label col-md-12" })
                                        <div class="col-md-12">
                                            @Html.DropDownList("TransportistaId", null, "Seleccionar...", htmlAttributes: new { @class = "form-control" })
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        @Html.Label("Cliente", "Cliente", htmlAttributes: new { @class = "control-label col-md-12" })
                                        <div class="col-md-12">
                                            @Html.DropDownList("ClienteId", null, "Seleccionar...", htmlAttributes: new { @class = "form-control select2" })
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.Label("Venta", htmlAttributes: new { @class = "control-label col-md-12" })
                                    <div class="col-md-10">
                                        @Html.DropDownList("VentaId", null, "Seleccionar...", htmlAttributes: new { @class = "form-control" })
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="card-footer  d-flex justify-content-center">
                            <input type="submit" id="btnBuscar" class="btn btn-outline-warning" value="Buscar" />
                        </div>
                    }
                </div>

            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="table-responsive" id="divTable">
            @Html.Partial("_Index", Model)
        </div>
    </div>
</div>

@section scripts{

    <script type="text/javascript">

        //$(document).ready(function () {

        //    //crearTabla(true);

        //    //$('#cboCantidad').change(function () {
        //    //    var value = $(this).val();
        //    //    crearTabla(value);

        //    //});


        //});

        @*var mensaje = '@ViewBag.mensaje';
        var tipoMensaje = '@ViewBag.tipoMensaje';



        if (tipoMensaje != '') {
            Swal.fire({
                position: 'top-end',
                icon: tipoMensaje,
                title: mensaje,
                showConfirmButton: false,
                timer: 1500
            })
        }*@

        function crearTabla(cant) {
            $("#divTable").hide();

            $("#preloader").fadeIn(5);


            var url = '@(Url.Action("GetRemitosFiltro", "Remitos", null, Request.Url.Scheme))';
                console.log(url);
                $("#divTable").load(url, function (response, status, xhr) {
                    console.log("aca se creo la tabla");
                    $("#divTable").show();
                    $("#preloader").fadeOut("slow");
                    if (status == "error") {
                        switch (xhr.status) {
                            case 408:
                                console.log(xhr.statusText, "Advertencia.");
                        }
                        return;
                    } else {
                        reloadDatatable();
                    }
                });
        }

        function onBeginSubmit() {
            $("#preloader").fadeIn(5);
        }
        function onCompleteSubmit() {
            $("#preloader").fadeOut("slow");
            reloadDatatable();
        }
        function onFailureResult() { }
        function onSuccessResult() { }


        $(function () {

            moment.locale('es');
            var start = moment().subtract(1, 'days');
            var end = moment();

            function cb(start, end) {
                $('#reportrange span').html(start.format('MMMM D, YYYY') + ' - ' + end.format('MMMM D, YYYY'));
                $('#txtFechas').val(start.format('DD/MM/YYYY') + ' - ' + end.format('DD/MM/YYYY'));
            }


            $('#reportrange').daterangepicker({
                startDate: start,
                endDate: end,

                ranges: {
                    'Hoy': [moment(), moment()],
                    'Ayer': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
                    'Últimos 7 Días': [moment().subtract(6, 'days'), moment()],
                    'Últimos 30 Días': [moment().subtract(29, 'days'), moment()],
                    'Este Mes': [moment().startOf('month'), moment().endOf('month')],
                    'Último Mes': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
                },
                "locale": {
                    "format": "DD/MM/YYYY",
                    "separator": " - ",
                    "applyLabel": "Aplicar",
                    "cancelLabel": "Cancelar",
                    "fromLabel": "De",
                    "toLabel": "Até",
                    "customRangeLabel": "Personalizado",
                    "daysOfWeek": [
                        "Dom",
                        "Lun",
                        "Mar",
                        "Mier",
                        "Jue",
                        "Vie",
                        "Sáb"
                    ],
                    "monthNames": [
                        "Enero",
                        "Febrero",
                        "Marzo",
                        "Abril",
                        "Mayo",
                        "Junio",
                        "Julio",
                        "Agosto",
                        "Septiembre",
                        "Octubre",
                        "Noviembre",
                        "Diciembre"
                    ],
                    "firstDay": 0
                }
            }, cb);

            cb(start, end);

        });


    </script>

    <script type="text/javascript">

        var mensaje = '@ViewBag.mensaje';
        var tipoMensaje = '@ViewBag.tipoMensaje';
        $('#btnVentas').removeAttr("hidden");

        if (tipoMensaje != '') {
            Swal.fire({
                position: 'top-end',
                icon: tipoMensaje,
                title: mensaje,
                showConfirmButton: false,
                timer: 3000
            }).then((result) => {
                if (result.isConfirmed) {
                    $('#AjaxForm').submit();
                }
            })
        } else {
            $('#btnVentas').text("Ir a Ventas");
        }

        function eliminar(id) {

            Swal.fire({
                title: 'Seguro desea eliminar?',
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Sí, eliminar!',
                cancelButtonText: 'Cancelar'
            }).then((result) => {
                if (result.isConfirmed) {
                    eliminacionConfirmada(id);
                }
            });


        }

        function eliminacionConfirmada(id) {
            $.ajax({
                url: "@(Url.Action("Delete"))",
                type: "POST",
                beforeSend: function () {
                    $("#preloader").fadeIn(5);
                },
                complete: function () {
                    $("#preloader").fadeOut("slow");
                },
                data: {
                    id: id
                },
                success: function (data) {
                    if (data.Success) {
                        Swal.fire(
                            'Eliminado!',
                            'El remito fue eliminado.',
                            'success'
                        ).then((result) => {
                            location.reload();
                        });
                    } else {
                        Swal.fire({
                            icon: 'error',
                            title: 'Ocurrió un Error!'
                        }).then((result) => {
                            location.reload();
                        });
                    }
                    //recargar pagina
                },
                error: function (XMLHttpRequest, textStatus, errorThrown) {
                    Swal.fire({
                        icon: 'error',
                        title: 'Ocurrió un Error!',
                        text: errorThrown
                    }).then((result) => {
                        location.reload();
                    });
                    //recargar pagina
                }
            });
        }

        function calularComision(total) {
            Swal.fire({
                title: 'El total del transportista es: $' + total,
                icon: 'info',
                showCancelButton: false,
                confirmButtonText: 'Ok',
                showLoaderOnConfirm: true
            }).then((result) => {
                if (result.isConfirmed) {
                    Swal.fire({
                        title: 'Ingresar en Porcentaje, la comisión (%)',
                        input: 'text',
                        inputAttributes: {
                            autocapitalize: 'off'
                        },
                        showCancelButton: true,
                        confirmButtonText: 'Calcular',
                        showLoaderOnConfirm: true
                    }).then((result) => {
                        if (result.isConfirmed) {
                            if (!isNumeric(result.value)) {
                                Swal.fire({
                                    icon: 'error',
                                    title: 'Debe ingresar una cantidad válida!'
                                });
                            } else {
                                var resultado = total * (result.value / 100);
                                Swal.fire({
                                    icon: 'success',
                                    title: 'La Comisión es de: $' + resultado.toString()
                                });
                            }
                        }
                    });
                }
            });
        }

    </script>

}