DistribuidoraApp/Controllers/ProductosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DistribuidoraAPI.Extensions;
using DistribuidoraAPI.Helpers;
using DistribuidoraAPI.Models;
using Microsoft.AspNet.Identity;
using Negocio.entidades;
using Negocio.enumeradores;
using Negocio.gestores;

namespace DistribuidoraAPI.Controllers
{
    [Authorize(Roles = "Administracion, Desarrollo")]
    [SessionExpire]
    public class ProductosController : Controller
    {
        private DistribuidoraDBEntities db = new DistribuidoraDBEntities();

        // GET: Productos
        public ActionResult Index()
        {
            List<Producto> listProductos = db.Producto.Include(p => p.Marca).Include(p => p.TipoDuracion).Include(p => p.TipoProducto).Where(p => p.Activo == true).ToList();

            List<ProductoStockViewModel> listProductoStockViewModel = new List<ProductoStockViewModel>();

            foreach (Producto item in listProductos)
            {
                listProductoStockViewModel.Add(new ProductoStockViewModel
                {
                    oProducto = item,
                    Cantidad = item.StockDeposito.Where(x => x.Activo == true).FirstOrDefault().Cantidad,
                    CantidadReservada = (decimal)item.StockDeposito.Where(x => x.Activo == true).FirstOrDefault().CantidadUsada,
                });
            }

            //listProductoStockViewModel = listProductos.Select(x => new ProductoStockViewModel
            //{
            //    oProducto = (Producto)x,
            //    Cantidad = x.StockDeposito.Where(x => x.Activo == true).FirstOrDefault().Cantidad,
            //    CantidadReservada = (decimal)x.StockDeposito.Where(x => x.Activo == true).FirstOrDefault().CantidadUsada,
            //}).ToList();
            return View(listProductoStockViewModel.ToList());
        }

        // GET: Productos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Producto producto = db.Producto.Find(id);
            if (producto == null)
            {
                return HttpNotFound();
            }
            return PartialView("_Details", producto);
        }

        // GET: Productos/Create
        public ActionResult Create()
        {
            ViewBag.MarcaId = new SelectList(db.Marca.Where(x => x.Activo == true), "MarcaId", "Nombre");
            ViewBag.TipoDuracionId = new SelectList(db.TipoDuracion.Where(x => x.Activo == true), "TipoDuracionId", "Nombre");
            ViewBag.TipoProductoId = new SelectList(db.TipoProducto.Where(x => x.Activo == true), "TipoProductoId", "Nombre");
            ViewBag.Depositos = new MultiSelectList(db.Deposito.Where(x => x.Activo == true), "DepositoId", "Nombre");
            ViewBag.ProveedorId = new SelectList(db.Proveedor.Where(x => x.Activo == true), "ProveedorId", "Nombre");

            return View();
        }

        // POST: Productos/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Codigo,DepositosList,TipoProductoId,TipoDuracionId,MarcaId,Nombre,PrecioCosto,Minimo,ProveedorId")] ProductoViewModel producto)
        {
            if (ModelState.IsValid)
            {
                Producto oProductoExistente = GestorProducto.getByCodigo(producto.Codigo);
                if (oProductoExistente != null)
                {
                    ModelState.AddModelError("Codigo", "El código ingresado ya existe");
                }
                else
                {
                    Producto oProducto = new Producto();
                    oProducto.TipoProductoId = producto.TipoProductoId;
                    oProducto.TipoDuracionId = producto.TipoDuracionId;
                    oProducto.MarcaId = producto.MarcaId;
                    oProducto.Nombre = producto.Nombre.ToUpper();
                    oProducto.PrecioCosto = producto.PrecioCosto;
                    oProducto.Minimo = producto.Minimo;
                    oProducto.Codigo = producto.Codigo;
                    oProducto.ProveedorId = producto.ProveedorId;
                    int[] depositosDefault = new int[1] { 1 };
                    producto.DepositosList = depositosDefault;

                    if (producto.DepositosList != null)
                    {
                        try
                        {
                            GestorEntidadesConexion.inicializarContexto();
                            GestorEntidadesConexion.beginTransaccion();
                            GestorProducto.Insertar(oProducto);
                            PrecioHelper.verificarPrecioLista(oProducto.ProductoId, 0);
                            if (ProductoHelper.guardarStockPorTipo(oProducto.ProductoId, 0, TipoStockE.Producto, producto.Cantidad, producto.DepositosList, TipoAccionE.Guardar))
                            {
                                GestorEntidadesConexion.commitTransaccion();
                                return RedirectToAction("Index");
                            }
                            else
                            {
                                GestorEntidadesConexion.rollbackTransaccion();
                                ModelState.AddModelError("", "No se pudo guardar el stock o existe algún problema.");
                            }
                        }
                        catch (Exception ex)
                        {
                            ModelState.AddModelError("", "Ocurrió un Error al intentar guardar los datos, y no se guardaron.");
                            GestorEntidadesConexion.rollbackTransaccion();
                        }
                        finally
                        {
                            GestorEntidadesConexion.disposeTransaccion();
                        }
                    }
                    else
                    {
                        ModelState.AddModelError("", "No se pudieron guardar los datos, seleccionar depósitos");
                    }
                }


            }
            else
            {
                ModelState.AddModelError("", "No se pudieron guardar los datos, revise los campos faltantes");
            }


            ViewBag.MarcaId = new SelectList(db.Marca.Where(x => x.Activo == true), "MarcaId", "Nombre", producto.MarcaId);
            ViewBag.TipoDuracionId = new SelectList(db.TipoDuracion.Where(x => x.Activo == true), "TipoDuracionId", "Nombre", producto.TipoDuracionId);
            ViewBag.TipoProductoId = new SelectList(db.TipoProducto.Where(x => x.Activo == true), "TipoProductoId", "Nombre", producto.TipoProductoId);
            ViewBag.ProveedorId = new SelectList(db.Proveedor.Where(x => x.Activo == true), "ProveedorId", "Nombre", producto.ProveedorId);

            if (producto.DepositosList != null)
            {
                ViewBag.Depositos = new MultiSelectList(db.Deposito.Where(x => x.Activo == true), "DepositoId", "Nombre", db.Deposito
                    .Where(x => producto.DepositosList.Contains(x.DepositoId)).Select(x => x.DepositoId).ToArray());
            }
            else
            {
                ViewBag.Depositos = new MultiSelectList(db.Deposito.Where(x => x.Activo == true), "DepositoId", "Nombre", producto.DepositosList);
            }

            return View(producto);
        }

        [HttpGet]
        public ActionResult AltaStock(int? id, int? tipoStock)
        {
            if (id == null || tipoStock == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            List<StockDeposito> listDepositoStockModel;
            if ((TipoStockE)tipoStock == TipoStockE.Producto)
            {
                listDepositoStockModel = GestorStock.getDepositosConStock((int)id, 0);
                Producto oProducto = GestorProducto.getById((int)id);
                ViewBag.Producto = oProducto.Nombre + " (" + oProducto.Marca.Nombre + ")";
                ViewBag.ProductoId = oProducto.ProductoId;
                ViewBag.ComboId = 0;
            }
            else
            {
                Combo oCombo = GestorCombo.getById((int)id);
                ViewBag.Combo = oCombo.Nombre + ", " + oCombo.Descripcion;
                listDepositoStockModel = GestorStock.getDepositosConStock(0, (int)id);
                ViewBag.ComboId = oCombo.ComboId;
                ViewBag.ProductoId = 0;
            }
            ViewBag.Depositos = new SelectList(db.Deposito.Where(x => x.Activo == true), "DepositoId", "Nombre");

            return View("AltaStock", listDepositoStockModel);
        }

        [HttpPost]
        public ActionResult AgregarStock(int? cboDepositos, double? txtCantidad, double? txtCantidadDisponible, int? ProductoId, int? ComboId)
        {
            if (cboDepositos == null || ProductoId == null || ComboId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            try
            {
                if (txtCantidad == null)
                {
                    txtCantidad = 0;
                }
                string descripcion = ""; string tipo = "";
                StockDeposito oStockDeposito = GestorStock.GetStockDeposito(cboDepositos.Value, (int)ProductoId, (int)ComboId);
                tipo = (ProductoId != 0) ? "Producto" : "Combo";
                descripcion = "Se actualizó el stock del " + tipo + ": " + ProductoId.ToString() + ". Cantidad original: " + oStockDeposito.Cantidad +

DistribuidoraApp/Views/Productos/AltaStock.cshtml
@model IEnumerable<Negocio.entidades.StockDeposito>

@{
    ViewBag.Title = "AltaStock";
}

<style type="text/css">
    .oculto {
        display: none;
    }
</style>

<div class="row">
    <div class="col-md-8">


        @if (ViewBag.Producto != null)
        {
            <h3>Listado de Stock en Depósitos del producto <strong>@ViewBag.Producto</strong></h3>
        }
        else
        {
            <h3>Listado de Stock en Depósitos del combo <strong>@ViewBag.Combo</strong></h3>
        }


    </div>
    <div class="col-md-4">
        <div>
            @if (ViewBag.Producto != null)
            {
                @Html.ActionLink("Volver al listado", "Index", "Productos", null, new { @class = "btn btn-warning pull-right" })
            }
            else
            {
                @Html.ActionLink("Volver al listado", "Index", "Combos", null, new { @class = "btn btn-warning pull-right" })
            }

        </div>
    </div>
    <hr />
</div>

<div class="row">
    <div class="col-md-12">
        <table class="table table-striped table-bordered datatable" data-excel="true" data-pdf="true" data-imprimir="true">
            <thead>
                <tr>
                    <th>
                        Depósito
                    </th>
                    <th>
                        Cantidad
                    </th>
                    <th>
                        Reservado
                    </th>
                    <th>
                        Disponible
                    </th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Deposito.Nombre)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Cantidad)
                        </td>

                        @{
                            decimal resultado = (decimal)item.Cantidad - (decimal)item.CantidadUsada;

                            string cantidadReservada = resultado.ToString();
                        }
                        <td>
                            @cantidadReservada
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.CantidadUsada)
                        </td>
                        <td>
                            <input value="Seleccionar" data-id="@item.DepositoId" data-cant="@item.Cantidad" data-reservado="@cantidadReservada" data-disponible="@item.CantidadUsada" data class="btn btn-sm btn-primary btnSelect" />
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

<div id="cardStock" class="card text-center oculto">
    @using (Html.BeginForm("AgregarStock", "Productos", FormMethod.Post))
    {
        <div class="card-header">
            Actualizar Stock
        </div>
        <div class="card-body form">
            <h5 class="card-title">Ingresar la cantidad</h5>
            @*<div class="row form">*@
            @*<div class="col-md-4">
                    <div class="form-group">
                        <label class="control-label col-md-10">Depósitos</label>
                        <div class="col-md-12">
                            @Html.DropDownList("cboDepositos", (SelectList)ViewBag.Depositos, htmlAttributes: new { @class = "form-control" })
                        </div>
                    </div>
                </div>*@
            <div class="row">
                @Html.Hidden("cboDepositos", 1)
                <div class="col-md-2">
                    <div class="form-group">
                        <label class="control-label col-md-10">Stock</label>
                        <div class="col-md-12">
                            <label id="lblCantidad" class="control-label"></label>
                        </div>
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="form-group">
                        <label class="control-label col-md-10">Reservado</label>
                        <div class="col-md-12">
                            <label id="lblReservado" class="control-label"></label>
                        </div>
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="form-group">
                        <label class="control-label col-md-10">Disponible</label>
                        <div class="col-md-12">
                            <label id="lblDisponible" class="control-label"></label>
                        </div>
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="form-group">
                        <label class="control-label col-md-10">Agregar Stock</label>
                        <div class="col-md-12">
                            <input class="form-control" type="number" id="txtCantidad" name="txtCantidad" />
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        <label class="control-label col-md-10">Actualizar Disp.</label>
                        <div class="col-md-12">
                            <input class="form-control" type="number" id="txtCantidadDisponible" name="txtCantidadDisponible" />
                        </div>
                    </div>
                </div>
            </div>
            <hr />
            <div class="row">
                <div class="col-md-8 d-flex justify-content-center">
                    <input class="btn btn-outline-success btn-block submit" type="submit" id="btnActualizar" value="Actualizar Stock" />
                </div>
                <div class="col-md-4 d-flex justify-content-center">
                    <button type="button" id="btnCancelar" class="btn btn-danger btn-block">Cancelar</button>
                </div>
            </div>

            @Html.Hidden("ProductoId", (object)ViewBag.ProductoId)
            @Html.Hidden("ComboId", (object)ViewBag.ComboId)
            @*</div>*@
        </div>
    }
</div>

@section scripts{

    <script type="text/javascript">
        $('.btnSelect').click(function () {
            var id = $(this).data('id');
            var cant = $(this).data('cant');
            var reservado = $(this).data('reservado');
            var disponible = $(this).data('disponible');

            if (id != null) {
                $('#cboDepositos').val(id);
                $('#lblCantidad').text(cant);
                $('#lblReservado').text(reservado);
                $('#lblDisponible').text(disponible);
                $('#cardStock').removeClass('oculto');
            }
        })

        $('#btnCancelar').click(function () {
            $('#cboDepositos').val('');
            $('#lblCantidad').text('');
            $('#txtCantidad').val('');
            $('#cardStock').addClass('oculto');
        })
    </script>

}

DistribuidoraApp/Views/Productos/AltaStockMasiva.cshtml
@model IEnumerable<Negocio.entidades.StockDeposito>
@using Microsoft.AspNet.Identity;
@using DistribuidoraAPI.Extensions;
@{
    ViewBag.Title = "Actualización Masiva de Stock";
}


<div class="row">
    <div class="col-md-8">
        <h3>Listado de Productos - Stock</h3>
    </div>
    <div class="col-md-4">
        <div>
            @Html.ActionLink("Volver al listado", "Index", "Home", null, new { @class = "btn btn-warning pull-right" })
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="card">
            @using (Ajax.BeginForm("AltaStockMasivaBusqueda", "Productos", null, new AjaxOptions
            {
                HttpMethod = "POST",
                OnBegin = "onBeginSubmit",
                OnComplete = "onCompleteSubmit",
                OnFailure = "onFailureResult",
                OnSuccess = "onSuccessResult",
                UpdateTargetId = "divTable",
                InsertionMode = InsertionMode.Replace
            }, new { id = "AjaxForm" }))
            {
                <div class="card-header">Filtros</div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-3">
                            <div class="form-group">
                                @Html.Label("Proveedor", "Proveedor", htmlAttributes: new { @class = "control-label col-md-12" })
                                <div class="col-md-12">
                                    @Html.DropDownList("ProveedorId", null, "Seleccionar...", htmlAttributes: new { @class = "form-control" })
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                @Html.Label("Marca", "Marca", htmlAttributes: new { @class = "control-label col-md-12" })
                                <div class="col-md-12">
                                    @Html.DropDownList("MarcaId", null, "Seleccionar...", htmlAttributes: new { @class = "form-control" })
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                @Html.Label("Tipo Producto", "TipoProducto", htmlAttributes: new { @class = "control-label col-md-12" })
                                <div class="col-md-12">
                                    @Html.DropDownList("TipoProductoId", null, "Seleccionar...", htmlAttributes: new { @class = "form-control" })
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-footer  d-flex justify-content-center">
                    <div class="row  d-flex justify-content-center">
                        <input type="submit" id="btnBuscar" class="btn btn-success" value="Buscar" />
                    </div>
                </div>
            }
        </div>
    </div>
</div>
<br />
<div class="row">
    <div class="col-md-8">
        <div id="divPreventista">
            <button onclick="modificarStockGeneral()" class="btn btn-outline-info">Actualizar todo el stock</button>

        </div>
    </div>
</div>
<br />
<div class="row">
    <div class="col-md-12">
        <div class="table-responsive" id="divTable">
            @Html.Partial("_AltaStockMasiva", Model)
        </div>

    </div>
</div>

@*<hr />*@
<!-- Begin Page Content -->
<!--<div class="container-fluid">-->

    <!-- Page Heading -->
    <!--<h1 class="h3 mb-2 text-gray-800">Gráficos</h1>-->

    <!-- Content Row -->
    <!--<div class="row">

        <div class="col-xl-8 col-lg-7">-->

            <!-- Area Chart -->
            <!--<div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Area Chart</h6>
                </div>
                <div class="card-body">
                    <div class="chart-area">
                        <canvas id="myAreaChart"></canvas>
                    </div>
                    <hr>
                    Styling for the area chart can be found in the <code>/js/demo/chart-area-demo.js</code> file.
                </div>
            </div>

            

        </div>-->

        <!-- Donut Chart -->
        <!--<div class="col-xl-4 col-lg-5">
            <div class="card shadow mb-4">-->
                <!-- Card Header - Dropdown -->
                <!--<div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Donut Chart</h6>
                </div>-->
                <!-- Card Body -->
                <!--<div class="card-body">
                    <div class="chart-pie pt-4">
                        <canvas id="myPieChart"></canvas>
                    </div>
                    <hr>
                    Styling for the donut chart can be found in the <code>/js/demo/chart-pie-demo.js</code> file.
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-xl-12 col-lg-9">-->
            <!-- Bar Chart -->
            <!--<div id="anycanvas" class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Ventas</h6>
                </div>
                <div class="card-body">
                    <div class="chart-bar">
                        <canvas id="myBarChart"></canvas>
                    </div>
                    <hr>
                    <p id="barChartDescri"></p>
                </div>
            </div>
        </div>
    </div>
</div>-->
<!-- /.container-fluid -->

@section scripts{

    <!-- Page level plugins -->
    @*<script src="~/lib/admin/vendor/chart.js/Chart.min.js"></script>*@

    <!-- Page level custom scripts -->
    @*<script src="~/lib/admin/js/demo/chart-area-demo.js"></script>
    <script src="~/lib/admin/js/demo/chart-pie-demo.js"></script>
    <script src="~/lib/admin/js/demo/chart-bar-demo.js"></script>*@

    <script type="text/javascript">

        function modificarStock(e) {
            var id = $(e).attr("data-id");
            console.log(id);
            Swal.fire({
                title: 'Ingresar la cantidad a reponer',
                input: 'text',
                inputAttributes: {
                    autocapitalize: 'off'
                },
                showCancelButton: true,
                confirmButtonText: 'Aceptar',
                showLoaderOnConfirm: true,

            }).then((result) => {
                if (result.isConfirmed) {
                    var resultado = result.value;
                    if (!isNumeric(resultado)) {
                        Swal.fire({
                            icon: 'error',
                            title: 'Debe ingresar una cantidad válida!'
                        });
                    } else {
                        actualizarStockUnico(resultado, id);
                    }
                }
            });
        }

        function actualizarStockUnico(stock, id) {
            $.ajax({
                url: "@(Url.Action("ActualizarStockUnico", "Productos"))",
                type: "POST",
                beforeSend: function () {
                    $("#preloader").fadeIn(5);
                },
                complete: function () {
                    $("#preloader").fadeOut("slow");
                },
                data: { stock: stock, id: id},
                success: function (data) {
                    console.log(data);
                    if (data.Success == "True") {
                        Swal.fire({
                            position: 'top-end',
                            icon: data.icon,
                            title: data.Message,
                            showConfirmButton: false,
                            timer: 1500
                        }).then((result) => {
                            $('#AjaxForm').submit();
                        });
                    } else {
                        Swal.fire({
                            icon: data.icon,
                            title: data.Message,
                            text: data.error
                        });
                    }
                },
                error: function (XMLHttpRequest, textStatus, errorThrown) {
                    Swal.fire({
                        icon: 'error',
                        title: 'Ocurrió un Error!',
                        text: errorThrown
                    });
                }
            });
        }

        function onBeginSubmit() {
            $("#preloader").fadeIn(5);
        }

        function onCompleteSubmit() {
            $("#preloader").fadeOut("slow");
            reloadDatatableNoOrder();
        }

        function onFailureResult() { }

        function onSuccessResult() { }

        function modificarStockGeneral() {
            Swal.fire({
                title: 'Ingresar la cantidad a reponer',
                text: 'Recordar que se incrementará la cantidad ingresada a TODOS los productos que se listaron',
                input: 'text',
                inputAttributes: {
                    autocapitalize: 'off'
                },
                showCancelButton: true,
                confirmButtonText: 'Aceptar',
                showLoaderOnConfirm: true,

            }).then((result) => {
                if (result.isConfirmed) {
                    var resultado = result.value;
                    if (!isNumeric(resultado)) {
                        Swal.fire({
                            icon: 'error',
                            title: 'Debe ingresar una cantidad válida!'
                        });
                    } else {
                        actualizarStockGeneral(resultado);
                    }
                }
            });
        }

        function getStockIds() {
            var idStocks = [];
            $("#tablaProductos").find('tr').each(function (i, k) {
                var $tds = $(this).find('td'),
                    StockId = $tds.eq(0).text().trim();
                if (StockId != "") {
                    idStocks.push(StockId);
                }
            });
            return idStocks;
        }

        function actualizarStockGeneral(cantidadGeneral) {
            var StockIds = getStockIds();
            console.log(StockIds);
            $.ajax({
                url: "@(Url.Action("ActualizarStockGeneral", "Productos"))",
                type: "POST",
                beforeSend: function () {
                    $("#preloader").fadeIn(5);
                },
                complete: function () {
                    $("#preloader").fadeOut("slow");
                },
                data: { cantidad: cantidadGeneral, stockIds: StockIds},
                success: function (data) {
                    console.log(data);
                    if (data.Success == "True") {
                        Swal.fire({
                            position: 'top-end',
                            icon: data.icon,
                            title: data.Message,
                            showConfirmButton: false,
                            timer: 1500
                        }).then((result) => {
                            $('#AjaxForm').submit();
                        });
                    } else {
                        Swal.fire({
                            icon: data.icon,
                            title: data.Message,
                            text: data.error
                        });
                    }
                },
                error: function (XMLHttpRequest, textStatus, errorThrown) {
                    Swal.fire({
                        icon: 'error',
                        title: 'Ocurrió un Error! No se pudieron obtener los clientes',
                        text: errorThrown
                    });
                }
            });
        }

    </script>



    @*<script type="text/javascript">

        function obtenerVentas() {
            $.ajax({
                url: "@(Url.Action("GetVentasChart", "Ventas"))",
                type: "GET",
                beforeSend: function () {
                    $("#preloader").fadeIn(5);
                },
                complete: function () {
                    $("#preloader").fadeOut("slow");
                },
                //data: { cantidad: cantidadGeneral, stockIds: StockIds},
                success: function (data) {
                    console.log(data);
                    if (data.Success == "True") {
                        $('#barChartDescri').html(data.descri);
                        createBarChart(data.x, data.y, data.x.length, data.y.length, data.y[data.y.length]);
                    }
                },
                error: function (XMLHttpRequest, textStatus, errorThrown) {
                    Swal.fire({
                        icon: 'error',
                        title: 'Ocurrió un Error! No se pudo obtener el gráfico',
                        text: errorThrown
                    });
                }
            });
        }


        $(document).ready(function () {
            obtenerVentas();
        })


    </script>*@
}