DistribuidoraApp/Controllers/CombosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using DistribuidoraAPI.Helpers;
using DistribuidoraAPI.Models;
using Negocio.entidades;
using Negocio.enumeradores;
using Negocio.gestores;
using Newtonsoft.Json;

namespace DistribuidoraAPI.Controllers
{
    [Authorize(Roles = "Administracion, Desarrollo")]
    [SessionExpire]
    public class CombosController : Controller
    {
        private DistribuidoraDBEntities db = new DistribuidoraDBEntities();

        // GET: Combos
        public ActionResult Index()
        {
            List<Combo> listCombos = db.Combo.Where(p => p.Activo == true).OrderByDescending(x => x.ComboId).ToList();

            return View(listCombos);
        }

        // GET: Combos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Combo combo = db.Combo.Find(id);
            if (combo == null)
            {
                return HttpNotFound();
            }
            return PartialView("_Details", combo);
        }

        // GET: Combos/Create
        public ActionResult Create()
        {
            ComboViewModel combo = new ComboViewModel();
            combo.MultiProductos = new List<Producto>();
            ViewBag.Multi = new MultiSelectList(new List<Producto>(), "ProductoId", "Nombre");
            // ViewBag.Depositos = new MultiSelectList(db.Deposito.Where(x => x.Activo == true), "DepositoId", "Nombre");
            ViewBag.Productos = new SelectList(db.Producto.Include(p => p.TipoProducto).Where(x => x.Activo == true), "ProductoId", "Nombre", "TipoProducto.Nombre");
            return View(combo);
        }

        // POST: Combos/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Nombre,Descripcion,PrecioCosto,Codigo")] ComboViewModel oComboViewModel, int[] Multi)
        {
            if (ModelState.IsValid)
            {
                if (Multi != null)
                {
                    oComboViewModel.Minimo = 99999999;
                    int[] depositos = new int[1] { 1 };
                    oComboViewModel.DepositosList = depositos;
                    oComboViewModel.Nombre = oComboViewModel.Nombre.ToUpper();
                    Combo oCombo = ComboHelper.guardarCombo(oComboViewModel, Multi);
                    PrecioHelper.verificarPrecioLista(0, oCombo.ComboId);
                    return RedirectToAction("Index");
                    //return RedirectToAction("AltaStock", "Productos", new { id = oCombo.ComboId, tipoStock = 2 });

                    //if (ProductoHelper.guardarStockPorTipo(0, oCombo.ComboId, TipoStockE.Combo, 0, oComboViewModel.DepositosList, TipoAccionE.Guardar))
                    //{

                    //}
                    //else
                    //{
                    //    ModelState.AddModelError("", "Ocurrió un Error al intentar guardar los datos, y no se guardaron.");
                    //}


                }
                else
                {
                    ModelState.AddModelError("", "Debe agregar Productos que compongan el Combo");
                }
            }

            if (Multi == null) ModelState.AddModelError("", "Debe agregar Productos que compongan el Combo");

            List<Producto> listProductos = new List<Producto>();
            if (Multi != null)
            {
                foreach (int i in Multi)
                {
                    listProductos.Add(GestorProducto.getById(i));
                }
            }
            oComboViewModel.MultiProductos = listProductos.ToList();
            ViewBag.Multi = new MultiSelectList(listProductos.ToList(), "ProductoId", "Nombre");
            ViewBag.Productos = new SelectList(db.Producto.Include(p => p.TipoProducto).Where(x => x.Activo == true), "ProductoId", "Nombre");
            //if (oComboViewModel.DepositosList != null)
            //{
            //    ViewBag.Depositos = new MultiSelectList(db.Deposito.Where(x => x.Activo == true), "DepositoId", "Nombre", db.Deposito
            //        .Where(x => oComboViewModel.DepositosList.Contains(x.DepositoId)).Select(x => x.DepositoId).ToArray());
            //}
            //else
            //{
            //    ViewBag.Depositos = new MultiSelectList(db.Deposito.Where(x => x.Activo == true), "DepositoId", "Nombre", oComboViewModel.DepositosList);
            //}
            return View(oComboViewModel);
        }

        public ActionResult GetPrecios(int?[] valores)
        {
            PrecioCustom precioCustom = new PrecioCustom();
            decimal Costo, VentaMayorista, VentaMinorista;
            Costo = 0; VentaMayorista = 0; VentaMinorista = 0;

            foreach (int ProductoId in valores)
            {
                Producto oProducto = GestorProducto.getById(ProductoId);
                Costo += (decimal)oProducto.PrecioCosto;
            }

            precioCustom.Costo = Costo.ToString();
            precioCustom.VentaMayorista = VentaMayorista.ToString();
            precioCustom.VentaMinorista = VentaMinorista.ToString();

            return Json(precioCustom);
        }

        // GET: Combos/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Combo oCombo = db.Combo.Find(id);
            if (oCombo == null)
            {
                return HttpNotFound();
            }
            ComboViewModel oComboViewModel = new ComboViewModel();
            oComboViewModel.ComboId = oCombo.ComboId;
            oComboViewModel.Nombre = oCombo.Nombre;
            oComboViewModel.Descripcion = oCombo.Descripcion;
            oComboViewModel.PrecioCosto = oCombo.PrecioCosto;
            oComboViewModel.Minimo = oCombo.Minimo;
            oComboViewModel.Codigo = oCombo.Codigo;

            List<Producto> listProductos = oCombo.ComboProducto.Where(x => x.Activo == true).Select(x => x.Producto).ToList();
            oComboViewModel.MultiProductos = listProductos;
            ViewBag.Multi = new MultiSelectList(listProductos, "ProductoId", "Nombre");
            ViewBag.Productos = new SelectList(db.Producto.Include(p => p.TipoProducto).Where(x => x.Activo == true), "ProductoId", "Nombre", "TipoProducto.Nombre");
            //ViewBag.Depositos = new MultiSelectList(db.Deposito.Where(x => x.Activo == true), "DepositoId", "Nombre", oCombo.StockDeposito
            //    .Where(x => x.ProductoId == oCombo.ComboId && x.Activo == true)
            //    .Select(x => x.DepositoId).ToArray());
            return View(oComboViewModel);
        }

        // POST: Combos/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ComboId,Nombre,Descripcion,PrecioCosto,Codigo")] ComboViewModel oComboViewModel, int[] Multi)
        {
            if (ModelState.IsValid)
            {
                if (Multi != null)
                {
                    int[] depositos = new int[1] { 1 };
                    oComboViewModel.DepositosList = depositos;
                    oComboViewModel.Nombre = oComboViewModel.Nombre.ToUpper();
                    if (ComboHelper.editarCombo(oComboViewModel, Multi))
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        ModelState.AddModelError("", "Ocurrió un Error al intentar guardar los datos, y no se guardaron.");
                    }
                }
                else
                {
                    ModelState.AddModelError("", "Debe agregar Productos que compongan el Combo");
                }
            }
            else
            {
                ModelState.AddModelError("", "Ocurrió un Error al intentar guardar los datos, y no se guardaron.");
            }
            if (Multi == null) ModelState.AddModelError("", "Debe agregar Productos que compongan el Combo");

            List<Producto> listProductos = new List<Producto>();
            if (Multi != null)
            {
                foreach (int i in Multi)
                {
                    listProductos.Add(GestorProducto.getById(i));
                }
            }
            oComboViewModel.MultiProductos = listProductos.ToList();
            ViewBag.Multi = new MultiSelectList(listProductos.ToList(), "ProductoId", "Nombre");
            ViewBag.Productos = new SelectList(db.Producto.Include(p => p.TipoProducto).Where(x => x.Activo == true), "ProductoId", "Nombre");
            // ViewBag.Depositos = new MultiSelectList(db.Deposito.Where(x => x.Activo == true), "DepositoId", "Nombre", oComboViewModel.DepositosList);
            return View(oComboViewModel);
        }

        [HttpPost]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Combo combo = db.Combo.Find(id);
            if (combo == null)
            {
                return HttpNotFound();
            }
            try
            {
                combo.Activo = false;

DistribuidoraApp/Views/Combos/Create.cshtml
@model DistribuidoraAPI.Models.ComboViewModel

@{
    ViewBag.Title = "Crear Nuevo Combo";
}

<style type="text/css">
    .negrita {
        font-weight: bold
    }
</style>

<div class="row">
    <div class="col-md-8">
        <h2>Crear Nuevo Combo</h2>
    </div>
    <div class="col-md-4">
        <div>
            @Html.ActionLink("Volver al listado", "Index", null, new { @class = "btn btn-warning pull-right" })
        </div>
    </div>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal form">
        <div class="row">
            <div class="col-md-6">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-12">
                        @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-12">
                        @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
                    </div>
                </div>

                @Html.LabelFor(model => model.MultiProductos, "Productos Incluidos en el Combo", htmlAttributes: new { @class = "control-label col-md-6" })
                <div class="form">
                    <div class="form-row">
                        <div class="form-group col-md-8">
                            <div class="col-md-12">
                                @Html.DropDownList("Productos", (SelectList)ViewBag.Productos, htmlAttributes: new { @class = "form-control js-example-basic-single" })
                            </div>
                        </div>
                        <div class="form-group col-md-4">
                            <div class="col-md-12">
                                <input type="number" id="Cantidad" placeholder="Cantidad" class="form-control required" />
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-12">
                            <input type="button" id="btnAgregar" value="Agregar" class="btn btn-info btn-block submit" />
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-10">
                        <em><b>Mantener apretada la tecla CTRL (Control) para seleccionar varios</b></em>
                        @Html.DropDownList("Multi", (MultiSelectList)ViewBag.MultiProductos, htmlAttributes: new { size = 8, multiple = "multiple", @class = "form-control" })
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <div class="col-md-12">
                            <input type="button" id="btnQuitar" value="Quitar" class="btn btn-warning btn-block" />
                        </div>
                    </div>
                    <div class="form-group col-md-6">
                        <div class="col-md-12">
                            <input type="button" id="btnLimpiar" value="Limpiar" class="btn btn-danger btn-block" />
                        </div>
                    </div>
                </div>
                <hr />
                @*<div class="form-group">
                        @Html.Label("Depósitos", htmlAttributes: new { @class = "control-label col-md-2" })

                        <div class="col-md-10">
                            <em><b>Mantener apretada la tecla CTRL (Control) para seleccionar varios</b></em>
                            @Html.DropDownList("DepositosList", (MultiSelectList)ViewBag.Depositos, htmlAttributes: new { size = 8, multiple = "multiple", @class = "form-control" })

                        </div>
                    </div>*@
                <div class="col-md-12">
                    <div class="alert alert-info">
                        <div class="alert-heading">
                            <p><b>Precio de Costo</b></p>
                        </div>
                        <br />
                        <p><b>Se muestran precios estimativos, sumando los precios de costo de cada producto que componen el combo</b></p>
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-8">
                        @Html.LabelFor(model => model.PrecioCosto, "Precio de Costo", htmlAttributes: new { @class = "control-label col-md-12" })
                        <div class="col-md-12">
                            @Html.EditorFor(model => model.PrecioCosto, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.PrecioCosto, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group col-md-4">
                        <br />
                        <label id="lblCosto" class="control-label col-md-2"></label>
                    </div>
                </div>
                @*<div class="form-row">
                        <div class="form-group col-md-6">
                            @Html.LabelFor(model => model.Minimo, "Mínimo", htmlAttributes: new { @class = "control-label col-md-12" })
                            <div class="col-md-12">
                                @Html.EditorFor(model => model.Minimo, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Minimo, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>*@
                <div class="form-group">
                    @Html.LabelFor(model => model.Codigo, "Código", htmlAttributes: new { @class = "control -label col-md-2" })
                    <div class="col-md-12">
                        @Html.EditorFor(model => model.Codigo, new { htmlAttributes = new { @class = "form-control" } })
                        @*<div class="input-group">

                                <div class="input-group-append">
                                    <input type="button" id="btnGenerarCodigo" value="Auto-Generar Código" class="btn-sm btn-primary" />
                                </div>
                            </div>*@
                        @Html.ValidationMessageFor(model => model.Codigo, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Crear Combo" class="btn btn-outline-success submit" />
                    </div>
                </div>
            </div>
        </div>
    </div>
}

@section scripts{

    <script type="text/javascript">
        $(document).ready(function () {

            //$('#MonedaARS').attr('name', 'customRadio');
            //$('#MonedaUSD').attr('name', 'customRadio');

            //$('.js-example-basic-single').select2();

            $('#btnAgregar').on('click', function () {
                var producto = $("#Productos :selected");
                var cantidad = $("#Cantidad").val();
                for (var i = 0; i < cantidad; i++) {
                    var nums = document.getElementById("Multi");
                    var numOption = new Option(producto.text(), producto.val());
                    nums.appendChild(numOption)
                }
                calcularPrecios();
            });

            $('#btnQuitar').on('click', function () {
                $('#Multi option').each(function () {
                    if ($(this)[0].selected) {
                        $(this)[0].remove();
                    }
                });
                calcularPrecios();
            });

            $('#btnLimpiar').on('click', function () {
                $('#Multi option').each(function () {
                    $(this)[0].remove();
                });
                calcularPrecios();
            });

            @*$('#MonedaUSD').on('click', function () {
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("GetPrecioDolar", "Combos")',
                    contentType: "application/json; charset=utf-8",
                    dataType: "json",
                    success: successFunc,
                    error: errorFunc
                });

                function successFunc(data, status) {
                    let count = data.lenght;
                    var result = [];

                    for (var i in data)
                        result.push(data[i].casa);
                    console.log(result);
                    for (var i = 0; i < result.length; i++) {
                        let objeto = result[i];
                        if (objeto.nombre === 'Dolar Oficial') {
                            console.log(objeto);
                            $('#lblDolar').text('Precio Dólar Oficial: $' + objeto.venta);
                        }
                    }
                }

                function errorFunc() {
                    console.log('error');
                }
            });

            $('#MonedaARS').on('click', function () {
                $('#lblDolar').text('');
            });*@

            $(this).submit(function (e) {
                $("#Multi option").prop("selected", "selected");
                calcularPrecios();
            });

            function calcularPrecios() {
                if ($('#Multi option').length > 0) {
                    var count = $('#Multi option').length;
                    var element = $('#Multi')[0];
                    let array = [];
                    for (var i = 0; i < count; i++) {
                        var id = element[0].value;
                        array.push(id);
                    }

                    var data = JSON.stringify({
                        'valores': array
                    });

                    $.ajax({
                        type: "POST",
                        url: '@Url.Action("GetPrecios", "Combos")',
                        data: data,
                        contentType: "application/json; charset=utf-8",
                        dataType: "json",
                        success: successFunc,
                        error: errorFunc
                    });

                    function successFunc(data, status) {
                        console.log(data);
                        $('#PrecioCosto').val(data.Costo);
                    }

                    function errorFunc() {
                        console.log('error');
                    }
                } else {
                    $('#PrecioCosto').val('');
                }
            }

        });
    </script>

}

DistribuidoraApp/Views/Combos/Edit.cshtml
@model DistribuidoraAPI.Models.ComboViewModel

@{
    ViewBag.Title = "Editar Combo";
}

<style type="text/css">
    .negrita {
        font-weight: bold
    }
</style>

<div class="row">
    <div class="col-md-8">
        <h2>Editar Combo</h2>
    </div>
    <div class="col-md-4">
        <div>
            @Html.ActionLink("Volver al listado", "Index", null, new { @class = "btn btn-warning" })
        </div>
    </div>
</div>

@using (Html.BeginForm("Edit", "Combos", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <div class="row">
            <div class="col-md-6">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.ComboId)

                <div class="form-group">
                    @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
                    </div>
                </div>

                @Html.LabelFor(model => model.MultiProductos, "Productos Incluidos en el Combo", htmlAttributes: new { @class = "control-label col-md-6" })
                <div class="form">
                    <div class="form-row">
                        <div class="form-group col-md-8">
                            <div class="col-md-12">
                                @Html.DropDownList("Productos", (SelectList)ViewBag.Productos, htmlAttributes: new { @class = "form-control js-example-basic-single" })
                            </div>
                        </div>
                        <div class="form-group col-md-4">
                            <div class="col-md-12">
                                <input type="number" id="Cantidad" placeholder="Cantidad" class="form-control" />
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-12">
                            <input type="button" id="btnAgregar" value="Agregar" class="btn btn-info btn-block submit" />
                        </div>
                    </div>
                </div>


                <div class="form-group">
                    <div class="col-md-10">
                        <em><b>Mantener apretada la tecla CTRL (Control) para seleccionar varios</b></em>
                        @Html.DropDownList("Multi", (MultiSelectList)ViewBag.MultiProductos, htmlAttributes: new { size = 8, multiple = "multiple", @class = "form-control" })
                    </div>
                </div>

                <div class="form-row">
                    <div class="form-group col-md-6">
                        <div class="col-md-12">
                            <input type="button" id="btnQuitar" value="Quitar" class="btn btn-warning btn-block" />
                        </div>
                    </div>
                    <div class="form-group col-md-6">
                        <div class="col-md-12">
                            <input type="button" id="btnLimpiar" value="Limpiar" class="btn btn-danger btn-block" />
                        </div>
                    </div>
                </div>
                <hr />

                <div class="col-md-12">
                    <div class="alert alert-info">
                        <div class="alert-heading">
                            <p><b>Precio de Costo, Venta Minorista y Venta Mayorista</b></p>
                        </div>
                        <br />
                        <p><b>Se muestran precios estimativos, sumando los precios de cada producto que componen el combo</b></p>
                    </div>
                </div>

                <div class="form-row">
                    <div class="form-group col-md-8">
                        @Html.LabelFor(model => model.PrecioCosto, "Precio de Costo", htmlAttributes: new { @class = "control-label col-md-12" })
                        <div class="col-md-12">
                            @Html.EditorFor(model => model.PrecioCosto, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.PrecioCosto, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group col-md-4">
                        <br />
                        <label id="lblCosto" class="control-label col-md-2"></label>
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Codigo, "Código", htmlAttributes: new { @class = "control -label col-md-2" })
                    <div class="col-md-12">
                        @Html.EditorFor(model => model.Codigo, new { htmlAttributes = new { @class = "form-control" } })
                        @*<div class="input-group">

                                <div class="input-group-append">
                                    <input type="button" id="btnGenerarCodigo" value="Auto-Generar Código" class="btn-sm btn-primary" />
                                </div>
                            </div>*@
                        @Html.ValidationMessageFor(model => model.Codigo, "", new { @class = "text-danger" })
                    </div>
                </div>


                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Editar Combo" class="btn btn-outline-success submit" />
                    </div>
                </div>
            </div>
        </div>
    </div>
}

@section scripts{

    <script type="text/javascript">
        $(document).ready(function () {


            $('.js-example-basic-single').select2();

            $('#btnAgregar').on('click', function () {
                var producto = $("#Productos :selected");
                var cantidad = $("#Cantidad").val();
                for (var i = 0; i < cantidad; i++) {
                    var nums = document.getElementById("Multi");
                    var numOption = new Option(producto.text(), producto.val());
                    nums.appendChild(numOption)
                }
                calcularPrecios();
            });

            $('#btnQuitar').on('click', function () {
                $('#Multi option').each(function () {
                    if ($(this)[0].selected) {
                        $(this)[0].remove();
                    }
                });
                calcularPrecios();
            });

            $('#btnLimpiar').on('click', function () {
                $('#Multi option').each(function () {
                    $(this)[0].remove();
                });
                calcularPrecios();
            });

          
            $(this).submit(function (e) {
                $("#Multi option").prop("selected", "selected");
                calcularPrecios();
            });

            function calcularPrecios() {
                if ($('#Multi option').length > 0) {
                    var count = $('#Multi option').length;
                    var element = $('#Multi')[0];
                    let array = [];
                    for (var i = 0; i < count; i++) {
                        var id = element[0].value;
                        array.push(id);
                    }

                    var data = JSON.stringify({
                        'valores': array
                    });

                    $.ajax({
                        type: "POST",
                        url: '@Url.Action("GetPrecios", "Combos")',
                        data: data,
                        contentType: "application/json; charset=utf-8",
                        dataType: "json",
                        success: successFunc,
                        error: errorFunc
                    });

                    function successFunc(data, status) {
                        console.log(data);
                        $('#PrecioCosto').val(data.Costo);
                        $('#PrecioVentaMayorista').val(data.VentaMayorista)
                        $('#PrecioVentaMinorista').val(data.VentaMinorista)
                    }

                    function errorFunc() {
                        console.log('error');
                    }
                } else {
                    $('#PrecioCosto').val('');
                    $('#PrecioVentaMayorista').val('')
                    $('#PrecioVentaMinorista').val('')
                }
            }

        });
    </script>

}